### ISSUE TITLE
Not working on 1.0.0

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-alarmcallback-jabber#1]
Hello,

Current version does not send XMPP messages and throws following stack trace on official allinone docker image (https://github.com/Graylog2/graylog2-images/tree/master/docker) when you click on "test alarm" button.
```
2015-03-13_16:56:27.25516 2015-03-13 16:56:27,251 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception in transport layer. This is likely a bug, closing channel.
2015-03-13_16:56:27.25520 java.lang.NoClassDefFoundError: Could not initialize class org.jivesoftware.smack.SmackConfiguration
2015-03-13_16:56:27.25520 	at org.jivesoftware.smack.ConnectionConfiguration.<init>(ConnectionConfiguration.java:67)
2015-03-13_16:56:27.25520 	at org.graylog2.alarmcallbacks.jabber.JabberAlarmCallback.call(JabberAlarmCallback.java:122)
2015-03-13_16:56:27.25521 	at org.graylog2.rest.resources.streams.alerts.StreamAlertReceiverResource.sendDummyAlert(StreamAlertReceiverResource.java:168)
2015-03-13_16:56:27.25521 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2015-03-13_16:56:27.25521 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2015-03-13_16:56:27.25521 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-03-13_16:56:27.25521 	at java.lang.reflect.Method.invoke(Method.java:497)
2015-03-13_16:56:27.25522 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
2015-03-13_16:56:27.25522 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
2015-03-13_16:56:27.25522 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:172)
2015-03-13_16:56:27.25522 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
2015-03-13_16:56:27.25523 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
2015-03-13_16:56:27.25523 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
2015-03-13_16:56:27.25523 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
2015-03-13_16:56:27.25523 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
2015-03-13_16:56:27.25526 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
2015-03-13_16:56:27.25533 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
2015-03-13_16:56:27.25534 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
2015-03-13_16:56:27.25534 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
2015-03-13_16:56:27.25534 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
2015-03-13_16:56:27.25534 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
2015-03-13_16:56:27.25534 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
2015-03-13_16:56:27.25535 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
2015-03-13_16:56:27.25535 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
2015-03-13_16:56:27.25535 	at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
2015-03-13_16:56:27.25540 	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
2015-03-13_16:56:27.25542 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
2015-03-13_16:56:27.25542 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
2015-03-13_16:56:27.25543 	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
2015-03-13_16:56:27.25544 	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
2015-03-13_16:56:27.25545 	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
2015-03-13_16:56:27.25546 	at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
2015-03-13_16:56:27.25547 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-03-13_16:56:27.25547 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-03-13_16:56:27.25548 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dennisoelkers** [comment]
Thanks for reporting this. How did you install the plugin?

**Comment by pdepaepe** [comment]
Hello and thanks to handle this,

git clone, mvn clean install for the plugin

Dockerfile:

FROM graylog2/allinone
COPY alarmcallback-jabber-1.1.0-SNAPSHOT.jar /opt/graylog/plugin/alarmcallback-jabber-1.1.0-SNAPSHOT.jar
CMD ["/opt/graylog/embedded/share/docker/my_init"]

On Web-UI, Stream => Manage alert => Alert callbacks => Jabber Alarm callback
I also filled an email address to get the "Test alarm button" visible.

Did i missed something ?

**Comment by dennisoelkers** [comment]
I found the cause for this problem. Unfortunately the fix needed to be done in the graylog server repository, so it will be included in either 1.0.2 or 1.1.0, whichever is released first.

**Comment by favadi** [comment]
@dennisoelkers I still have this error with graylog2 1.0.2. Is your fix already merged in this version?

**Comment by joschi** [comment]
@favadi The fix is part of Graylog 1.0.2: Graylog2/graylog2-server@75871dd6544c1515c642b927056b0c7e006309e6
